import type {
  Incident,
  Organization,
  ProfileActivity,
  Report,
  ResearchRequest,
  VolunteerOpportunity,
} from "./types"

export const CURRENT_USER = {
  id: "u-ariana",
  name: "Ariana",
  location: "Atlanta, GA",
  lat: 33.7701,
  lng: -84.3702,
}

export const ORGANIZATIONS: Organization[] = [
  {
    id: "org-crk",
    name: "Chattahoochee Riverkeeper",
    description: "Protecting and restoring the Chattahoochee River watershed through science and advocacy.",
    categories: ["Water", "Wildlife", "Conservation"],
    logoColor: "#0369a1",
  },
  {
    id: "org-trees",
    name: "Trees Atlanta",
    description: "Growing and protecting Atlanta's urban forest through planting and restoration.",
    categories: ["Trees", "Conservation", "Climate"],
    logoColor: "#16a34a",
  },
  {
    id: "org-piedmont",
    name: "Piedmont Park Conservancy",
    description: "Preserving and enhancing Piedmont Park for the community.",
    categories: ["Community", "Litter", "Conservation"],
    logoColor: "#059669",
  },
  {
    id: "org-audubon",
    name: "Georgia Audubon",
    description: "Building places where birds and people thrive across Georgia.",
    categories: ["Wildlife", "Education", "Conservation"],
    logoColor: "#ca8a04",
  },
]

// Reports clustered as a smoke event in NW Atlanta (feed the AI incident)
const smokeCluster: Report[] = [
  {
    id: "r-smoke-1",
    userId: "u-102",
    userName: "Marcus D.",
    category: "smoke-fire",
    tags: ["smoke", "air quality"],
    description: "Thick smoke drifting from the northwest. Sky is hazy and it smells like burning wood.",
    image: "/reports/smoke.png",
    latitude: 33.8121,
    longitude: -84.4468,
    approximateLocation: "Near Bolton, NW Atlanta",
    severity: "high",
    createdAt: "2026-09-24T14:12:00Z",
    confirmationCount: 9,
    incidentId: "inc-smoke",
  },
  {
    id: "r-smoke-2",
    userId: "u-118",
    userName: "Priya S.",
    category: "smoke-fire",
    tags: ["smoke", "haze"],
    description: "Can see a grey plume from the highway. Air quality feels poor.",
    image: "/reports/smoke.png",
    latitude: 33.8203,
    longitude: -84.438,
    approximateLocation: "Near I-285 NW, Atlanta",
    severity: "high",
    createdAt: "2026-09-24T14:40:00Z",
    confirmationCount: 6,
    incidentId: "inc-smoke",
  },
  {
    id: "r-smoke-3",
    userId: "u-140",
    userName: "Jordan W.",
    category: "air-pollution",
    tags: ["air quality", "haze"],
    description: "Strong smoke smell, hard to breathe outside. Keeping windows closed.",
    latitude: 33.8047,
    longitude: -84.451,
    approximateLocation: "Riverside, NW Atlanta",
    severity: "moderate",
    createdAt: "2026-09-24T15:05:00Z",
    confirmationCount: 4,
    incidentId: "inc-smoke",
  },
  {
    id: "r-smoke-4",
    userId: "u-155",
    userName: "Elena R.",
    category: "smoke-fire",
    tags: ["smoke", "fire"],
    description: "Visible haze over the tree line, ash settling on cars.",
    image: "/reports/smoke.png",
    latitude: 33.815,
    longitude: -84.458,
    approximateLocation: "Whittier Mill, NW Atlanta",
    severity: "severe",
    createdAt: "2026-09-24T15:22:00Z",
    confirmationCount: 11,
    incidentId: "inc-smoke",
  },
]

const waterCluster: Report[] = [
  {
    id: "r-water-1",
    userId: "u-201",
    userName: "Sam T.",
    category: "water-pollution",
    tags: ["water", "runoff"],
    description: "Oily sheen and foam along the river bank near the trail. Water looks discolored.",
    image: "/reports/water.png",
    latitude: 33.9015,
    longitude: -84.4602,
    approximateLocation: "Chattahoochee River, NW",
    severity: "high",
    createdAt: "2026-09-22T11:30:00Z",
    confirmationCount: 8,
    incidentId: "inc-water",
  },
  {
    id: "r-water-2",
    userId: "u-210",
    userName: "Nia B.",
    category: "water-pollution",
    tags: ["water", "debris"],
    description: "Cloudy brown water with debris collecting near the bank.",
    image: "/reports/water.png",
    latitude: 33.9088,
    longitude: -84.451,
    approximateLocation: "Chattahoochee River, Paces",
    severity: "moderate",
    createdAt: "2026-09-22T13:10:00Z",
    confirmationCount: 5,
    incidentId: "inc-water",
  },
]

const standaloneReports: Report[] = [
  {
    id: "r-litter-1",
    userId: "u-ariana",
    userName: "Ariana",
    category: "litter",
    tags: ["litter", "park"],
    description: "Recurring litter buildup near the northeast entrance benches. Bottles and wrappers.",
    image: "/reports/litter.png",
    latitude: 33.7873,
    longitude: -84.3728,
    approximateLocation: "Piedmont Park, NE entrance",
    severity: "moderate",
    createdAt: "2026-09-20T09:15:00Z",
    confirmationCount: 12,
  },
  {
    id: "r-tree-1",
    userId: "u-305",
    userName: "Devon K.",
    category: "damaged-tree",
    tags: ["storm", "tree"],
    description: "Large oak split and fell across the lawn after last night's storm.",
    image: "/reports/tree.png",
    latitude: 33.7561,
    longitude: -84.3641,
    approximateLocation: "Atlanta BeltLine, Eastside Trail",
    severity: "moderate",
    createdAt: "2026-09-19T08:00:00Z",
    confirmationCount: 3,
  },
  {
    id: "r-wildlife-1",
    userId: "u-312",
    userName: "Grace L.",
    category: "wildlife",
    tags: ["wildlife", "birds"],
    description: "Great blue heron spotted along the creek. Healthy and active.",
    image: "/reports/wildlife.png",
    latitude: 33.7649,
    longitude: -84.3512,
    approximateLocation: "Freedom Park Creek, Atlanta",
    severity: "low",
    createdAt: "2026-09-18T17:45:00Z",
    confirmationCount: 7,
  },
  {
    id: "r-flood-1",
    userId: "u-320",
    userName: "Tomas V.",
    category: "flooding",
    tags: ["flooding", "storm"],
    description: "Street flooding at the underpass after heavy rain. Water over the curb.",
    image: "/reports/flooding.png",
    latitude: 33.7402,
    longitude: -84.4009,
    approximateLocation: "West End, Atlanta",
    severity: "high",
    createdAt: "2026-09-21T19:30:00Z",
    confirmationCount: 6,
    incidentId: "inc-flood",
  },
  {
    id: "r-flood-2",
    userId: "u-322",
    userName: "Aisha M.",
    category: "flooding",
    tags: ["flooding"],
    description: "Low road fully covered with water, cars turning around.",
    image: "/reports/flooding.png",
    latitude: 33.7365,
    longitude: -84.4102,
    approximateLocation: "West End, Atlanta",
    severity: "high",
    createdAt: "2026-09-21T20:05:00Z",
    confirmationCount: 4,
    incidentId: "inc-flood",
  },
  {
    id: "r-recycle-1",
    userId: "u-330",
    userName: "Leo P.",
    category: "recycling",
    tags: ["recycling"],
    description: "Overflowing recycling bins with mixed waste at the transit stop.",
    latitude: 33.7712,
    longitude: -84.3901,
    approximateLocation: "Downtown Atlanta",
    severity: "low",
    createdAt: "2026-09-17T12:00:00Z",
    confirmationCount: 2,
  },
  {
    id: "r-invasive-1",
    userId: "u-340",
    userName: "Hana C.",
    category: "invasive-species",
    tags: ["invasive", "plants"],
    description: "Kudzu spreading aggressively over native shrubs along the trail edge.",
    latitude: 33.7501,
    longitude: -84.34,
    approximateLocation: "Atlanta BeltLine, Southside",
    severity: "moderate",
    createdAt: "2026-09-16T10:20:00Z",
    confirmationCount: 5,
  },
  {
    id: "r-light-1",
    userId: "u-350",
    userName: "Owen F.",
    category: "light-pollution",
    tags: ["light", "night"],
    description: "New floodlights left on all night, very bright over the residential block.",
    latitude: 33.78,
    longitude: -84.42,
    approximateLocation: "West Midtown, Atlanta",
    severity: "low",
    createdAt: "2026-09-15T23:10:00Z",
    confirmationCount: 1,
  },
  // Out-of-region reports demonstrating scalability
  {
    id: "r-beach-1",
    userId: "u-401",
    userName: "Carmen O.",
    category: "beach-coastal",
    tags: ["coastal", "plastic"],
    description: "Plastic debris washing up along the shoreline after the tide.",
    image: "/reports/beach.png",
    latitude: 32.0018,
    longitude: -80.8456,
    approximateLocation: "Tybee Island, GA",
    severity: "moderate",
    createdAt: "2026-09-14T08:40:00Z",
    confirmationCount: 9,
  },
  {
    id: "r-wildfire-1",
    userId: "u-410",
    userName: "Dana H.",
    category: "smoke-fire",
    tags: ["wildfire", "smoke"],
    description: "Wildfire smoke rolling over the ridge, air quality alert in effect.",
    image: "/reports/smoke.png",
    latitude: 37.5, // outside main region
    longitude: -119.5,
    approximateLocation: "Sierra foothills, CA",
    severity: "severe",
    createdAt: "2026-09-13T16:00:00Z",
    confirmationCount: 14,
  },
  {
    id: "r-flood-3",
    userId: "u-420",
    userName: "Ravi N.",
    category: "flooding",
    tags: ["flooding", "coastal"],
    description: "Bayou overflow flooding the neighborhood street.",
    image: "/reports/flooding.png",
    latitude: 29.76,
    longitude: -95.37,
    approximateLocation: "Houston, TX",
    severity: "high",
    createdAt: "2026-09-12T09:20:00Z",
    confirmationCount: 6,
  },
]

export const SEED_REPORTS: Report[] = [
  ...smokeCluster,
  ...waterCluster,
  ...standaloneReports,
]

export const SEED_INCIDENTS: Incident[] = [
  {
    id: "inc-smoke",
    title: "Wildfire / Smoke Event",
    category: "smoke-fire",
    description:
      "Multiple community members are reporting smoke, haze, and poor air quality across northwest Atlanta within a short window. These reports appear to describe the same developing event.",
    latitude: 33.8135,
    longitude: -84.449,
    reportIds: smokeCluster.map((r) => r.id),
    reportCount: 27,
    firstReportedAt: "2026-09-24T14:12:00Z",
    lastReportedAt: "2026-09-24T15:22:00Z",
    severity: "severe",
    aiGrouped: true,
    groupingConfidenceLabel: "Likely related",
    approximateLocation: "Northwest Atlanta",
    status: "monitoring",
  },
  {
    id: "inc-water",
    title: "Water pollution concern",
    category: "water-pollution",
    description:
      "Several reports describe discolored water, foam, and an oily sheen along the same stretch of the Chattahoochee River. Potentially related to upstream runoff.",
    latitude: 33.905,
    longitude: -84.455,
    reportIds: waterCluster.map((r) => r.id),
    reportCount: 14,
    firstReportedAt: "2026-09-22T11:30:00Z",
    lastReportedAt: "2026-09-22T13:10:00Z",
    severity: "high",
    aiGrouped: true,
    groupingConfidenceLabel: "Potentially related",
    approximateLocation: "Chattahoochee River, NW",
    status: "responding",
  },
  {
    id: "inc-flood",
    title: "Flash flooding cluster",
    category: "flooding",
    description:
      "Reports of street flooding concentrated around West End after heavy evening rainfall. Likely the same weather-driven event.",
    latitude: 33.7384,
    longitude: -84.4055,
    reportIds: ["r-flood-1", "r-flood-2"],
    reportCount: 8,
    firstReportedAt: "2026-09-21T19:30:00Z",
    lastReportedAt: "2026-09-21T20:05:00Z",
    severity: "high",
    aiGrouped: true,
    groupingConfidenceLabel: "Likely related",
    approximateLocation: "West End, Atlanta",
    status: "monitoring",
  },
]

export const SEED_VOLUNTEER: VolunteerOpportunity[] = [
  {
    id: "vol-1",
    organizationId: "org-piedmont",
    organizationName: "Piedmont Park Conservancy",
    title: "Park Cleanup",
    description:
      "Join neighbors to clear litter along the northeast paths and meadow. Gloves and bags provided.",
    location: "Piedmont Park",
    latitude: 33.7879,
    longitude: -84.3733,
    date: "Saturday",
    time: "9:00 AM",
    duration: "1.5 hours",
    distanceMiles: 2.4,
    categories: ["Litter", "Community"],
    tags: ["Litter", "Parks"],
    capacity: 40,
    registeredCount: 26,
    setting: "Outdoor",
    skillLevel: "Beginner",
    relatedReportId: "r-litter-1",
  },
  {
    id: "vol-2",
    organizationId: "org-trees",
    organizationName: "Trees Atlanta",
    title: "Tree Planting",
    description: "Help plant native trees to expand the urban canopy. Training provided on site.",
    location: "Atlanta",
    latitude: 33.749,
    longitude: -84.388,
    date: "Sunday",
    time: "10:00 AM",
    duration: "2 hours",
    distanceMiles: 3.1,
    categories: ["Trees", "Conservation"],
    tags: ["Trees", "Conservation"],
    capacity: 30,
    registeredCount: 18,
    setting: "Outdoor",
    skillLevel: "Any",
    relatedReportId: "r-tree-1",
  },
  {
    id: "vol-3",
    organizationId: "org-crk",
    organizationName: "Chattahoochee Riverkeeper",
    title: "River Cleanup",
    description:
      "Wade and paddle to remove debris from the riverbank and collect water-quality samples.",
    location: "Chattahoochee River",
    latitude: 33.9015,
    longitude: -84.4602,
    date: "Saturday",
    time: "8:30 AM",
    duration: "3 hours",
    distanceMiles: 5.8,
    categories: ["Water", "Wildlife"],
    tags: ["Water", "Wildlife"],
    capacity: 25,
    registeredCount: 20,
    setting: "Outdoor",
    skillLevel: "Intermediate",
    relatedReportId: "r-water-1",
  },
  {
    id: "vol-4",
    organizationId: "org-audubon",
    organizationName: "Georgia Audubon",
    title: "Bird Habitat Survey",
    description: "Learn to identify local species and log observations for conservation research.",
    location: "Freedom Park",
    latitude: 33.7649,
    longitude: -84.3512,
    date: "Sunday",
    time: "7:30 AM",
    duration: "2 hours",
    distanceMiles: 1.9,
    categories: ["Wildlife", "Education"],
    tags: ["Wildlife", "Education"],
    capacity: 20,
    registeredCount: 9,
    setting: "Outdoor",
    skillLevel: "Beginner",
    relatedReportId: "r-wildlife-1",
  },
  {
    id: "vol-5",
    organizationId: "org-trees",
    organizationName: "Trees Atlanta",
    title: "Invasive Species Removal",
    description: "Help remove kudzu and English ivy to protect native plants along the BeltLine.",
    location: "Atlanta BeltLine",
    latitude: 33.7501,
    longitude: -84.34,
    date: "Saturday",
    time: "9:30 AM",
    duration: "2.5 hours",
    distanceMiles: 4.2,
    categories: ["Conservation", "Trees"],
    tags: ["Conservation", "Restoration"],
    capacity: 35,
    registeredCount: 12,
    setting: "Outdoor",
    skillLevel: "Any",
    relatedReportId: "r-invasive-1",
  },
  {
    id: "vol-6",
    organizationId: "org-piedmont",
    organizationName: "Coastal Georgia Alliance",
    title: "Beach Cleanup",
    description: "Remove plastic and debris from the shoreline to protect coastal wildlife.",
    location: "Tybee Island",
    latitude: 32.0018,
    longitude: -80.8456,
    date: "Saturday",
    time: "9:00 AM",
    duration: "3 hours",
    distanceMiles: 12.4,
    categories: ["Litter", "Water", "Wildlife"],
    tags: ["Coastal", "Litter"],
    capacity: 50,
    registeredCount: 31,
    setting: "Outdoor",
    skillLevel: "Beginner",
    relatedReportId: "r-beach-1",
  },
  {
    id: "vol-7",
    organizationId: "org-trees",
    organizationName: "Climate Action ATL",
    title: "Community Climate Workshop",
    description: "Indoor session on local climate resilience and how to organize neighborhood action.",
    location: "Downtown Atlanta",
    latitude: 33.7712,
    longitude: -84.3901,
    date: "Wednesday",
    time: "6:00 PM",
    duration: "1.5 hours",
    distanceMiles: 1.2,
    categories: ["Climate", "Education", "Community"],
    tags: ["Climate", "Education"],
    capacity: 60,
    registeredCount: 34,
    setting: "Indoor",
    skillLevel: "Any",
  },
]

export const SEED_RESEARCH: ResearchRequest[] = [
  {
    id: "res-1",
    researcherName: "Dr. Lena Ortiz",
    region: "Atlanta, GA",
    dateRange: "Jan 2026 – Sep 2026",
    categories: ["Air / Smoke", "Water Pollution"],
    purpose: "Studying seasonal air quality patterns and community exposure.",
    status: "approved",
    estimatedObservationCount: 1840,
    createdAt: "2026-09-10T00:00:00Z",
  },
  {
    id: "res-2",
    researcherName: "Coastal Ecology Lab",
    region: "Georgia Coast",
    dateRange: "Jun 2026 – Sep 2026",
    categories: ["Coastal", "Wildlife"],
    purpose: "Mapping coastal debris accumulation and wildlife impact.",
    status: "under-review",
    estimatedObservationCount: 612,
    createdAt: "2026-09-18T00:00:00Z",
  },
]

export const PROFILE_ACTIVITY: ProfileActivity[] = [
  { id: "a1", type: "report", label: "Reported litter", location: "Piedmont Park", date: "Sept 20" },
  { id: "a2", type: "volunteer", label: "Joined cleanup", location: "Atlanta BeltLine", date: "Sept 18" },
  { id: "a3", type: "report", label: "Reported smoke", location: "Atlanta", date: "Sept 12" },
  { id: "a4", type: "action", label: "Confirmed a nearby report", location: "Freedom Park", date: "Sept 10" },
  { id: "a5", type: "volunteer", label: "Registered for tree planting", location: "Atlanta", date: "Sept 8" },
]

export const COMMUNITY_MEMBERS = [
  { id: "u-102", name: "Marcus D.", location: "NW Atlanta", reports: 14, cause: "Air quality", color: "#dc2626" },
  { id: "u-201", name: "Sam T.", location: "Chattahoochee", reports: 9, cause: "Water", color: "#0369a1" },
  { id: "u-305", name: "Devon K.", location: "BeltLine", reports: 6, cause: "Trees", color: "#92400e" },
  { id: "u-312", name: "Grace L.", location: "Freedom Park", reports: 11, cause: "Wildlife", color: "#16a34a" },
  { id: "u-320", name: "Tomas V.", location: "West End", reports: 8, cause: "Flooding", color: "#2563eb" },
  { id: "u-340", name: "Hana C.", location: "BeltLine", reports: 5, cause: "Conservation", color: "#ca8a04" },
]

export const IMPACT_STATS = {
  observationsThisMonth: 2481,
  likelyIncidents: 1103,
  categories: 14,
  regions: 8,
}

export const CATEGORY_DISTRIBUTION = [
  { name: "Litter", value: 620 },
  { name: "Water", value: 410 },
  { name: "Air / Smoke", value: 356 },
  { name: "Wildlife", value: 298 },
  { name: "Flooding", value: 244 },
  { name: "Trees", value: 212 },
  { name: "Other", value: 341 },
]

export const REPORTS_OVER_TIME = [
  { month: "Jan", reports: 142 },
  { month: "Feb", reports: 168 },
  { month: "Mar", reports: 205 },
  { month: "Apr", reports: 241 },
  { month: "May", reports: 288 },
  { month: "Jun", reports: 312 },
  { month: "Jul", reports: 356 },
  { month: "Aug", reports: 389 },
  { month: "Sep", reports: 380 },
]

export const REGION_DISTRIBUTION = [
  { name: "Midtown", value: 34 },
  { name: "West End", value: 22 },
  { name: "NW Atlanta", value: 28 },
  { name: "BeltLine", value: 41 },
  { name: "Coastal", value: 15 },
]
